# Import output CSV files generated by write_phyloseq
pseq1 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "simple")

# Import mother .shared and .taxonomy and metadata files
pseq2 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "mothur")

# Import BIOM files
pseq3 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "biom")

BiocManager::install(c("kableExtra"))


#load data and packages

library(microbiome)
data(dietswap)
data(data(peerj32))
data(atlas1006)
pseq <- dietswap
pseq2 <- dietswap
pseq2 <- dietswap

#Global indicators

tab <- global(pseq, index = "all")
tab %>%
  kable() %>%
  kable_styling()


alpha
tab <- alpha(pseq, index = "all")
tab %>%
  kable() %>%
  kable_styling()
%all can be changed to any index you need ex:chao1

tab <- richness(pseq)
tab %>%
  kable() %>%
  kable_styling()

tab <- dominance(pseq, index = "all")
tab %>%
  kable() %>%
  kable_styling()

tab <- rarity(pseq, index = "all")
tab %>%
  kable() %>%
  kable_styling()

tab <- evenness(pseq, "all")
tab %>%
  kable() %>%
  kable_styling()

#load data and packages

library(microbiome)
library(dplyr)
data(dietswap)
data <- dietswap

#Calculate group divergences between the African American and rural Africans based on dietswap data

divergence(subset_samples(dietswap, nationality == "AFR"))
am <- divergence(subset_samples(dietswap, nationality == "AAM"))

#view differences in sample diversity in a boxplot:

boxplot(list(American = am, African = af ))

